<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Lunet.Core\Lunet.Core.csproj" />
    <ProjectReference Include="..\..\src\Lunet.Editor\Lunet.Editor.csproj" />
    <ProjectReference Include="..\..\src\Lunet.Docs\Lunet.Docs.csproj" />
    <ProjectReference Include="..\..\src\Lunet.Compiler\Lunet.Compiler.csproj" />
    <ProjectReference Include="..\..\src\Lunet.Framework\Lunet.Framework.csproj" />
    <ProjectReference Include="..\..\src\Lunet.Runtime\Lunet.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
