<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Lunet</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);STBSHARP_INTERNAL</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Lunet.Tests" />
    <InternalsVisibleTo Include="Lunet.Android" />
  </ItemGroup>
</Project>
